
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OD_MASTER_H
#define OD_MASTER_H

#include "data.h"
#include "pdo.h"

#define OD_INPUT_PDO_COM        0x1400     //Master_ RPDOx index
#define OD_INPUT_PDO_MAP        0x1600
#define OD_OUTPUT_PDO_COM       0x1800     //Master_ TPDOx index
#define OD_OUTPUT_PDO_MAP       0x1A00


#define OD_INPUT_DATA_START     0x2200     //Data Value
#define OD_OUTPUT_DATA_START    0x2300     //Data Value

#define OD_BITLEN_16             0x0010    /* 16-bit */

#define GET_OD_INPUT_MAP(offset, n) \
    ( ((OD_INPUT_DATA_START + (offset)) << 16) \
    | ((n) << 8) \
    | OD_BITLEN_16 )

#define GET_OD_OUTPUT_MAP(offset, n) \
    ( ((OD_OUTPUT_DATA_START + (offset)) << 16) \
    | ((n) << 8) \
    | OD_BITLEN_16 )

#define COBID_DISABLE(cobid) ((cobid) | 0x80000000UL)
#define COBID_ENABLE(cobid)  ((cobid) & 0x7FFFFFFFUL)

#define GET_COBID_INPUT_PDO_COM(offset) (OD_INPUT_PDO_COM + offset)    
#define GET_COBID_INPUT_PDO_MAP(offset) (OD_INPUT_PDO_MAP + offset)    
#define GET_COBID_OUTPUT_PDO_COM(offset) (OD_OUTPUT_PDO_COM + offset)    
#define GET_COBID_OUTPUT_PDO_MAP(offset) (OD_OUTPUT_PDO_MAP + offset) 

#define GET_COBID_INPUT_PDO_DATA(offset) (OD_INPUT_DATA_START + offset)    
#define GET_COBID_OUTPUT_PDO_DATA(offset) (OD_OUTPUT_DATA_START + offset)

#define Slave_Prod_Heartbeat_MS 1000 // ms
#define GET_SLAVE_PROD_HEARTBEAT            (Slave_Prod_Heartbeat_MS)
#define GET_SLAVE_PROD_HEARTBEAT_CONSUMER   (Slave_Prod_Heartbeat_MS*5)

#define INPUT_TRANSMISSION_TYPE     TRANS_EVENT_PROFILE
#define OUTPUT_TRANSMISSION_TYPE    TRANS_EVENT_PROFILE

/* Prototypes of function provided by object dictionnary */
UNS32 Master_valueRangeTest (UNS8 typeValue, void * value);
const indextable * Master_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master_ node data struct */
extern CO_Data Master_Data;

#endif /* OD_MASTER_H */
